const char *sensor_names[DS_SENSOR_MAX_ID + 1] =
{
  "",

  CG_NAME_SENSOR_COUNTER,                                /* Base sensor types */
  CG_NAME_SENSOR_FREQUENCY,
  CG_NAME_SENSOR_TALLY,
  
  CG_NAME_SENSOR_PCS_FREQ_SIGNAL_RECEIVE,                /* Process sensor types. */
  CG_NAME_SENSOR_PCS_FREQ_SIGNAL_DROP,
  CG_NAME_SENSOR_PCS_FREQ_SIGNAL_CONSUME,
  CG_NAME_SENSOR_PCS_FREQ_SIGNAL_SAVE,
  CG_NAME_SENSOR_PCS_FREQ_SIGNAL_LOSE,
  CG_NAME_SENSOR_PCS_FREQ_SIGNAL_SEND,
  CG_NAME_SENSOR_PCS_FREQ_REQUEST,
  CG_NAME_SENSOR_PCS_FREQ_STATE,
  CG_NAME_SENSOR_PCS_COUNT_SIGNAL_RECEIVE,
  CG_NAME_SENSOR_PCS_COUNT_SIGNAL_DROP,
  CG_NAME_SENSOR_PCS_COUNT_SIGNAL_CONSUME,
  CG_NAME_SENSOR_PCS_COUNT_SIGNAL_SAVE,
  CG_NAME_SENSOR_PCS_COUNT_SIGNAL_LOSE,
  CG_NAME_SENSOR_PCS_COUNT_SIGNAL_SEND,
  CG_NAME_SENSOR_PCS_COUNT_REQUEST,
  CG_NAME_SENSOR_PCS_COUNT_STATE,
  CG_NAME_SENSOR_PCS_QUEUE_LENGTH,
  CG_NAME_SENSOR_PCS_QUEUE_CONTENT,
  CG_NAME_SENSOR_PCS_WAITTIME_SIGNAL,
  CG_NAME_SENSOR_PCS_WAITTIME_STATE,
  CG_NAME_SENSOR_PCS_RESPONSETIME_REQUEST,
  CG_NAME_SENSOR_PCS_TRANSMISSIONTIME_SIGNAL,
  CG_NAME_SENSOR_PCS_FREQ_TRANSITION,
  CG_NAME_SENSOR_PCS_COUNT_TRANSITION,

  CG_NAME_SENSOR_MACH_FREQ_REQUEST,                      /* Machine sensor types. */
  CG_NAME_SENSOR_MACH_COUNT_REQUEST,
  CG_NAME_SENSOR_MACH_QUEUE_LENGTH,
  CG_NAME_SENSOR_MACH_QUEUE_CONTENT,
  CG_NAME_SENSOR_MACH_UTILIZATION,
  CG_NAME_SENSOR_MACH_WAITTIME_REQUEST,
  CG_NAME_SENSOR_MACH_THROUGHPUT,
  CG_NAME_SENSOR_MACH_SERVICETIME_REQUEST,

  CG_NAME_SENSOR_SYS_FREQ_SIGNAL,                        /* System sensor types. */
  CG_NAME_SENSOR_SYS_FREQ_REQUEST,
  CG_NAME_SENSOR_SYS_FREQ_PROCESS_CREATE,
  CG_NAME_SENSOR_SYS_FREQ_PROCESS_STOP,
  CG_NAME_SENSOR_SYS_COUNT_SIGNAL,
  CG_NAME_SENSOR_SYS_COUNT_REQUEST,
  CG_NAME_SENSOR_SYS_COUNT_PROCESS_CREATE,
  CG_NAME_SENSOR_SYS_COUNT_PROCESS_STOP,
  CG_NAME_SENSOR_SYS_LIFETIME_PROCESS,
  ""
};

const char * sensor_operator_names[] =
{
  "GetSumOfSamples",
  "GetSumInt",
  "GetSumPerTime",
  "GetSumPerTimeInt",
  "GetAbsFreq",
  "GetRelFreq",
  "GetLastValue",
  "GetCurrentValue",
  "GetLastSample",
  "GetNumOfSamples",
  "GetNumInt",
  "GetMinimum",
  "GetMaximum",
  "GetSumSquare",
  "GetAverage",
  "GetAvgInt",
  "GetVariance",
  "GetStdDev",
  "GetVarCoeff"
};
